name 'mtna_server'
maintainer 'Jonathan Porta'
maintainer_email 'jonathan@jonathanPorta.com'
license 'WTFPL'
description 'Configures a fedora 24 server that runs the mtna software'
long_description 'Configures mtna server'
version '0.0.1'
source_url 'https://github.com/PronghornDigital/mtna-server-cookbook'
issues_url 'https://github.com/PronghornDigital/mtna-server-cookbook/issues'

depends 'packagecloud'
depends 'firewall'
